version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh docker-entrypoint.sh
    environment:
      SEAWATCH_PLANNER: "dev"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
