# Generated by Django 2.2.6 on 2019-11-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'permissions': (('can_assess_profiles', 'Set assessments for profiles'),)},
        ),
    ]
