# Generated by Django 2.2.6 on 2019-10-24 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
                ('second_citizenship', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('country_of_birth', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male'), ('d', 'diverse')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('needs_schengen_visa', models.BooleanField()),
                ('phone', models.CharField(max_length=100)),
                ('emergency_contact', models.TextField()),
                ('comments', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
