# Generated by Django 2.2.6 on 2019-10-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seawatch_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.BooleanField()),
                ('approved', models.BooleanField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seawatch_registration.Position')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seawatch_registration.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='profiles',
            field=models.ManyToManyField(through='seawatch_registration.ProfilePosition', to='seawatch_registration.Profile'),
        ),
    ]
