# Generated by Django 2.2.6 on 2019-10-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seawatch_registration', '0002_auto_20191024_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('ident', 'identification documents and visa'), ('nautic', 'nautical qualification'), ('engineer', 'engineer qualification'), ('seafarer', 'seafarer qualification'), ('other', 'other qualification')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('issuing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issuing_authority', models.CharField(max_length=100)),
                ('issuing_place', models.CharField(max_length=100)),
                ('issuing_country', models.CharField(max_length=100)),
                ('file', models.BinaryField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seawatch_registration.DocumentType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seawatch_registration.Profile')),
            ],
        ),
    ]
