# Generated by Django 2.2.6 on 2019-10-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seawatch_registration', '0003_document_documenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('group', models.CharField(choices=[('lang', 'language'), ('other', 'other')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_skills',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='seawatch_registration.Skill'),
        ),
    ]
