# Generated by Django 2.2.6 on 2019-11-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seawatch_registration', '0010_insert_seed data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='static/document/'),
        ),
    ]
