# Generated by Django 2.2.6 on 2019-11-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seawatch_registration', '0014_auto_20191113_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
