# Generated by Django 2.2.7 on 2019-12-16 14:47
from django.db import migrations


class Migration(migrations.Migration):

    def copy_name_from_profile_to_user(apps, schema_editor):
        Profile = apps.get_model('seawatch_registration', 'Profile')
        for profile in Profile.objects.all():
            user = profile.user
            user.first_name = profile.first_name
            user.last_name = profile.last_name
            user.save()

    dependencies = [
        ('seawatch_registration', '0017_auto_20191205_0919'),
    ]

    operations = [
        migrations.RunPython(copy_name_from_profile_to_user),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
