# Generated by Django 2.2.9 on 2020-01-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seawatch_registration', '0018_auto_20191210_1329'),
        ('seawatch_registration', '0019_auto_20191218_1306'),
    ]

    operations = [
    ]
