# Generated by Django 2.2.7 on 2020-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seawatch_registration', '0021_auto_20200123_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_de',
            field=models.CharField(max_length=500, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en_us',
            field=models.CharField(max_length=500, null=True, verbose_name='Text'),
        ),
    ]
