data = [
    {'code': 'AD', 'name': 'Andorra', 'demonym': 'Andorran'},
    {'code': 'AE', 'name': 'United Arab Emirates', 'demonym': 'Emirian'},
    {'code': 'AF', 'name': 'Afghanistan', 'demonym': 'Afghani'},
    {'code': 'AG', 'name': 'Antigua and Barbuda', 'demonym': 'Antiguan'},
    {'code': 'AI', 'name': 'Anguilla', 'demonym': 'Anguillan'},
    {'code': 'AL', 'name': 'Albania', 'demonym': 'Albanian'},
    {'code': 'AM', 'name': 'Armenia', 'demonym': 'Armenian'},
    {'code': 'AO', 'name': 'Angola', 'demonym': 'Angolan'},
    {'code': 'AQ', 'name': 'Antarctica', 'demonym': 'Antarctic'},
    {'code': 'AR', 'name': 'Argentina', 'demonym': 'Argentine'},
    {'code': 'AS', 'name': 'American Samoa', 'demonym': 'Samoan'},
    {'code': 'AT', 'name': 'Austria', 'demonym': 'Austrian'},
    {'code': 'AU', 'name': 'Australia', 'demonym': 'Australian'},
    {'code': 'AW', 'name': 'Aruba', 'demonym': 'Arubian'},
    {'code': 'AX', 'name': 'Åland Islands', 'demonym': 'Ålandic'},
    {'code': 'AZ', 'name': 'Azerbaijan', 'demonym': 'Azerbaijani'},
    {'code': 'BA', 'name': 'Bosnia and Herzegovina', 'demonym': 'Bosnian'},
    {'code': 'BB', 'name': 'Barbados', 'demonym': 'Barbadian'},
    {'code': 'BD', 'name': 'Bangladesh', 'demonym': 'Bangladeshi'},
    {'code': 'BE', 'name': 'Belgium', 'demonym': 'Belgian'},
    {'code': 'BF', 'name': 'Burkina Faso', 'demonym': 'Burkinabe'},
    {'code': 'BG', 'name': 'Bulgaria', 'demonym': 'Bulgarian'},
    {'code': 'BH', 'name': 'Bahrain', 'demonym': 'Bahrainian'},
    {'code': 'BI', 'name': 'Burundi', 'demonym': 'Burundian'},
    {'code': 'BJ', 'name': 'Benin', 'demonym': 'Beninese'},
    {'code': 'BL', 'name': 'Saint Barthélemy', 'demonym': 'Barthélemois'},
    {'code': 'BM', 'name': 'Bermuda', 'demonym': 'Bermudan'},
    {'code': 'BN', 'name': 'Brunei', 'demonym': 'Bruneian'},
    {'code': 'BO', 'name': 'Bolivia', 'demonym': 'Bolivian'},
    {'code': 'BQ', 'name': 'Caribbean Netherlands', 'demonym': ''},
    {'code': 'BR', 'name': 'Brazil', 'demonym': 'Brazilian'},
    {'code': 'BS', 'name': 'Bahamas', 'demonym': 'Bahameese'},
    {'code': 'BT', 'name': 'Bhutan', 'demonym': 'Bhutanese'},
    {'code': 'BV', 'name': 'Bouvet Island', 'demonym': ''},
    {'code': 'BW', 'name': 'Botswana', 'demonym': 'Motswana'},
    {'code': 'BY', 'name': 'Belarus', 'demonym': 'Belarusian'},
    {'code': 'BZ', 'name': 'Belize', 'demonym': 'Belizean'},
    {'code': 'CA', 'name': 'Canada', 'demonym': 'Canadian'},
    {'code': 'CC', 'name': 'Cocos (Keeling) Islands', 'demonym': 'Cocossian'},
    {'code': 'CD', 'name': 'Democratic Republic of the Congo', 'demonym': 'Congolese'},
    {'code': 'CF', 'name': 'Central African Republic', 'demonym': 'Central African'},
    {'code': 'CG', 'name': 'Congo (Republic of)', 'demonym': 'Congolese'},
    {'code': 'CH', 'name': 'Switzerland', 'demonym': 'Swiss'},
    {'code': 'CI', 'name': "Côte d'Ivoire (Ivory Coast)", 'demonym': 'Ivorian'},
    {'code': 'CK', 'name': 'Cook Islands', 'demonym': 'Cook Islander'},
    {'code': 'CL', 'name': 'Chile', 'demonym': 'Chilean'},
    {'code': 'CM', 'name': 'Cameroon', 'demonym': 'Cameroonian'},
    {'code': 'CN', 'name': 'China', 'demonym': 'Chinese'},
    {'code': 'CO', 'name': 'Colombia', 'demonym': 'Colombian'},
    {'code': 'CR', 'name': 'Costa Rica', 'demonym': 'Costa Rican'},
    {'code': 'CU', 'name': 'Cuba', 'demonym': 'Cuban'},
    {'code': 'CV', 'name': 'Cape Verde', 'demonym': 'Cape Verdean'},
    {'code': 'CW', 'name': 'Curaçao', 'demonym': 'Curaçaoan'},
    {'code': 'CX', 'name': 'Christmas Island', 'demonym': 'Christmas Islander'},
    {'code': 'CY', 'name': 'Cyprus', 'demonym': 'Cypriot'},
    {'code': 'CZ', 'name': 'Czech Republic', 'demonym': 'Czech'},
    {'code': 'DE', 'name': 'Germany', 'demonym': 'German'},
    {'code': 'DJ', 'name': 'Djibouti', 'demonym': 'Djiboutian'},
    {'code': 'DK', 'name': 'Denmark', 'demonym': 'Danish'},
    {'code': 'DM', 'name': 'Dominica', 'demonym': 'Dominican'},
    {'code': 'DO', 'name': 'Dominican Republic', 'demonym': 'Dominican'},
    {'code': 'DZ', 'name': 'Algeria', 'demonym': 'Algerian'},
    {'code': 'EC', 'name': 'Ecuador', 'demonym': 'Ecuadorean'},
    {'code': 'EE', 'name': 'Estonia', 'demonym': 'Estonian'},
    {'code': 'EG', 'name': 'Egypt', 'demonym': 'Egyptian'},
    {'code': 'EH', 'name': 'Western Saharan', 'demonym': 'Western Saharan'},
    {'code': 'ER', 'name': 'Eritrea', 'demonym': 'Eritrean'},
    {'code': 'ES', 'name': 'Spain', 'demonym': 'Spanish'},
    {'code': 'ET', 'name': 'Ethiopia', 'demonym': 'Ethiopian'},
    {'code': 'FI', 'name': 'Finland', 'demonym': 'Finnish'},
    {'code': 'FJ', 'name': 'Fiji', 'demonym': 'Fijian'},
    {'code': 'FK', 'name': 'Falkland Islands', 'demonym': 'Falkland Islander'},
    {'code': 'FM', 'name': 'Micronesia', 'demonym': 'Micronesian'},
    {'code': 'FO', 'name': 'Faroe Islands', 'demonym': 'Faroese'},
    {'code': 'FR', 'name': 'France', 'demonym': 'French'},
    {'code': 'GA', 'name': 'Gabon', 'demonym': 'Gabonese'},
    {'code': 'GB', 'name': 'United Kingdom', 'demonym': 'British'},
    {'code': 'GD', 'name': 'Grenada', 'demonym': 'Grenadian'},
    {'code': 'GE', 'name': 'Georgia', 'demonym': 'Georgian'},
    {'code': 'GF', 'name': 'French Guiana', 'demonym': 'French Guianese'},
    {'code': 'GG', 'name': 'Guernsey', 'demonym': ''},
    {'code': 'GH', 'name': 'Ghana', 'demonym': 'Ghanaian'},
    {'code': 'GI', 'name': 'Gibraltar', 'demonym': 'Gibraltarian'},
    {'code': 'GL', 'name': 'Greenland', 'demonym': 'Greenlander'},
    {'code': 'GM', 'name': 'Gambia', 'demonym': 'Gambian'},
    {'code': 'GN', 'name': 'Guinea', 'demonym': 'Guinean'},
    {'code': 'GP', 'name': 'Guadeloupe', 'demonym': 'Guadeloupean'},
    {'code': 'GQ', 'name': 'Equatorial Guinea', 'demonym': 'Equatorial Guinean'},
    {'code': 'GR', 'name': 'Greece', 'demonym': 'Greek'},
    {'code': 'GS', 'name': 'South Georgia and the South Sandwich Islands', 'demonym': ''},
    {'code': 'GT', 'name': 'Guatemala', 'demonym': 'Guatemalan'},
    {'code': 'GU', 'name': 'Guam', 'demonym': 'Guamanian'},
    {'code': 'GW', 'name': 'Guinea-Bissau', 'demonym': 'Guinean'},
    {'code': 'GY', 'name': 'Guyana', 'demonym': 'Guyanese'},
    {'code': 'HK', 'name': 'Hong Kong', 'demonym': 'Hong Konger'},
    {'code': 'HM', 'name': 'Heard and McDonald Islands', 'demonym': ''},
    {'code': 'HN', 'name': 'Honduras', 'demonym': 'Honduran'},
    {'code': 'HR', 'name': 'Croatia', 'demonym': 'Croatian'},
    {'code': 'HT', 'name': 'Haiti', 'demonym': 'Haitian'},
    {'code': 'HU', 'name': 'Hungary', 'demonym': 'Hungarian'},
    {'code': 'ID', 'name': 'Indonesia', 'demonym': 'Indonesian'},
    {'code': 'IE', 'name': 'Ireland', 'demonym': 'Irish'},
    {'code': 'IL', 'name': 'Israel', 'demonym': 'Israeli'},
    {'code': 'IM', 'name': 'Isle of Man', 'demonym': 'Manx'},
    {'code': 'IN', 'name': 'India', 'demonym': 'Indian'},
    {'code': 'IO', 'name': 'British Indian Ocean Territory', 'demonym': ''},
    {'code': 'IQ', 'name': 'Iraq', 'demonym': 'Iraqi'},
    {'code': 'IR', 'name': 'Iran', 'demonym': 'Iranian'},
    {'code': 'IS', 'name': 'Iceland', 'demonym': 'Icelander'},
    {'code': 'IT', 'name': 'Italy', 'demonym': 'Italian'},
    {'code': 'JE', 'name': 'Jersey', 'demonym': ''},
    {'code': 'JM', 'name': 'Jamaica', 'demonym': 'Jamaican'},
    {'code': 'JO', 'name': 'Jordan', 'demonym': 'Jordanian'},
    {'code': 'JP', 'name': 'Japan', 'demonym': 'Japanese'},
    {'code': 'KE', 'name': 'Kenya', 'demonym': 'Kenyan'},
    {'code': 'KG', 'name': 'Kyrgyzstan', 'demonym': 'Kyrgyzstani'},
    {'code': 'KH', 'name': 'Cambodia', 'demonym': 'Cambodian'},
    {'code': 'KI', 'name': 'Kiribati', 'demonym': 'I-Kiribati'},
    {'code': 'KM', 'name': 'Comoros', 'demonym': 'Comoran'},
    {'code': 'KN', 'name': 'Saint Kitts and Nevis', 'demonym': 'Kittian'},
    {'code': 'KP', 'name': 'North Korea', 'demonym': 'North Korean'},
    {'code': 'KR', 'name': 'South Korea', 'demonym': 'South Korean'},
    {'code': 'KW', 'name': 'Kuwait', 'demonym': 'Kuwaiti'},
    {'code': 'KY', 'name': 'Cayman Islands', 'demonym': 'Caymanian'},
    {'code': 'KZ', 'name': 'Kazakhstan', 'demonym': 'Kazakhstani'},
    {'code': 'LA', 'name': 'Laos', 'demonym': 'Laotian'},
    {'code': 'LB', 'name': 'Lebanon', 'demonym': 'Lebanese'},
    {'code': 'LC', 'name': 'Saint Lucia', 'demonym': 'Saint Lucian'},
    {'code': 'LI', 'name': 'Liechtenstein', 'demonym': 'Liechtensteiner'},
    {'code': 'LK', 'name': 'Sri Lanka', 'demonym': 'Sri Lankan'},
    {'code': 'LR', 'name': 'Liberia', 'demonym': 'Liberian'},
    {'code': 'LS', 'name': 'Lesotho', 'demonym': 'Mosotho'},
    {'code': 'LT', 'name': 'Lithuania', 'demonym': 'Lithunian'},
    {'code': 'LU', 'name': 'Luxembourg', 'demonym': 'Luxembourger'},
    {'code': 'LV', 'name': 'Latvia', 'demonym': 'Latvian'},
    {'code': 'LY', 'name': 'Libya', 'demonym': 'Libyan'},
    {'code': 'MA', 'name': 'Morocco', 'demonym': 'Moroccan'},
    {'code': 'MC', 'name': 'Monaco', 'demonym': 'Monacan'},
    {'code': 'MD', 'name': 'Moldova', 'demonym': 'Moldovan'},
    {'code': 'ME', 'name': 'Montenegro', 'demonym': 'Montenegrin'},
    {'code': 'MF', 'name': 'Saint Martin (France)', 'demonym': ''},
    {'code': 'MG', 'name': 'Madagascar', 'demonym': 'Malagasy'},
    {'code': 'MH', 'name': 'Marshall Islands', 'demonym': 'Marshallese'},
    {'code': 'MK', 'name': 'Macedonia', 'demonym': 'Macedonian'},
    {'code': 'ML', 'name': 'Mali', 'demonym': 'Malian'},
    {'code': 'MM', 'name': 'Burma (Republic of the Union of Myanmar)', 'demonym': 'Myanmarese'},
    {'code': 'MN', 'name': 'Mongolia', 'demonym': 'Mongolian'},
    {'code': 'MO', 'name': 'Macau', 'demonym': 'Macanese'},
    {'code': 'MP', 'name': 'Northern Mariana Islands', 'demonym': 'Northern Mariana Islander'},
    {'code': 'MQ', 'name': 'Martinique', 'demonym': 'Martinican'},
    {'code': 'MR', 'name': 'Mauritania', 'demonym': 'Mauritanian'},
    {'code': 'MS', 'name': 'Montserrat', 'demonym': 'Montserratian'},
    {'code': 'MT', 'name': 'Malta', 'demonym': 'Maltese'},
    {'code': 'MU', 'name': 'Mauritius', 'demonym': 'Mauritian'},
    {'code': 'MV', 'name': 'Maldives', 'demonym': 'Maldivan'},
    {'code': 'MW', 'name': 'Malawi', 'demonym': 'Malawian'},
    {'code': 'MX', 'name': 'Mexico', 'demonym': 'Mexican'},
    {'code': 'MY', 'name': 'Malaysia', 'demonym': 'Malaysian'},
    {'code': 'MZ', 'name': 'Mozambique', 'demonym': 'Mozambican'},
    {'code': 'NA', 'name': 'Namibia', 'demonym': 'Namibian'},
    {'code': 'NC', 'name': 'New Caledonia', 'demonym': 'New Caledonian'},
    {'code': 'NE', 'name': 'Niger', 'demonym': 'Nigerien'},
    {'code': 'NF', 'name': 'Norfolk Island', 'demonym': 'Norfolk Islander'},
    {'code': 'NG', 'name': 'Nigeria', 'demonym': 'Nigerian'},
    {'code': 'NI', 'name': 'Nicaragua', 'demonym': 'Nicaraguan'},
    {'code': 'NL', 'name': 'Netherlands', 'demonym': 'Dutch'},
    {'code': 'NO', 'name': 'Norway', 'demonym': 'Norwegian'},
    {'code': 'NP', 'name': 'Nepal', 'demonym': 'Nepalese'},
    {'code': 'NR', 'name': 'Nauru', 'demonym': 'Nauruan'},
    {'code': 'NU', 'name': 'Niue', 'demonym': 'Niuean'},
    {'code': 'NZ', 'name': 'New Zealand', 'demonym': 'New Zealander'},
    {'code': 'OM', 'name': 'Oman', 'demonym': 'Omani'},
    {'code': 'PA', 'name': 'Panama', 'demonym': 'Panamanian'},
    {'code': 'PE', 'name': 'Peru', 'demonym': 'Peruvian'},
    {'code': 'PF', 'name': 'French Polynesia', 'demonym': 'French Polynesian'},
    {'code': 'PG', 'name': 'Papua New Guinea', 'demonym': 'Papua New Guinean'},
    {'code': 'PH', 'name': 'Philippines', 'demonym': 'Filipino'},
    {'code': 'PK', 'name': 'Pakistan', 'demonym': 'Pakistani'},
    {'code': 'PL', 'name': 'Poland', 'demonym': 'Polish'},
    {'code': 'PM', 'name': 'St. Pierre and Miquelon', 'demonym': 'Saint-Pierrais'},
    {'code': 'PN', 'name': 'Pitcairn', 'demonym': 'Pitcairn Islander'},
    {'code': 'PR', 'name': 'Puerto Rico', 'demonym': 'Puerto Rican'},
    {'code': 'PS', 'name': 'Palestine', 'demonym': 'Palestinian'},
    {'code': 'PT', 'name': 'Portugal', 'demonym': 'Portuguese'},
    {'code': 'PW', 'name': 'Palau', 'demonym': 'Palauan'},
    {'code': 'PY', 'name': 'Paraguay', 'demonym': 'Paraguayan'},
    {'code': 'QA', 'name': 'Qatar', 'demonym': 'Qatari'},
    {'code': 'RE', 'name': 'Réunion', 'demonym': ''},
    {'code': 'RO', 'name': 'Romania', 'demonym': 'Romanian'},
    {'code': 'RS', 'name': 'Serbia', 'demonym': 'Serbian'},
    {'code': 'RU', 'name': 'Russian Federation', 'demonym': 'Russian'},
    {'code': 'RW', 'name': 'Rwanda', 'demonym': 'Rwandan'},
    {'code': 'SA', 'name': 'Saudi Arabia', 'demonym': 'Saudi Arabian'},
    {'code': 'SB', 'name': 'Solomon Islands', 'demonym': 'Solomon Islander'},
    {'code': 'SC', 'name': 'Seychelles', 'demonym': 'Seychellois'},
    {'code': 'SD', 'name': 'Sudan', 'demonym': 'Sudanese'},
    {'code': 'SE', 'name': 'Sweden', 'demonym': 'Swedish'},
    {'code': 'SG', 'name': 'Singapore', 'demonym': 'Singaporean'},
    {'code': 'SH', 'name': 'Saint Helena', 'demonym': 'Saint Helenian'},
    {'code': 'SI', 'name': 'Slovenia', 'demonym': 'Slovenian'},
    {'code': 'SJ', 'name': 'Svalbard and Jan Mayen Islands', 'demonym': ''},
    {'code': 'SK', 'name': 'Slovakia', 'demonym': 'Slovakian'},
    {'code': 'SL', 'name': 'Sierra Leone', 'demonym': 'Sierra Leonean'},
    {'code': 'SM', 'name': 'San Marino', 'demonym': 'Sanmarinese'},
    {'code': 'SN', 'name': 'Senegal', 'demonym': 'Senegalese'},
    {'code': 'SO', 'name': 'Somalia', 'demonym': 'Somali'},
    {'code': 'SR', 'name': 'Suriname', 'demonym': 'Surinamer'},
    {'code': 'SS', 'name': 'South Sudan', 'demonym': 'Sudanese'},
    {'code': 'ST', 'name': 'São Tome and Príncipe', 'demonym': 'São Tomean'},
    {'code': 'SV', 'name': 'El Salvador', 'demonym': 'Salvadorean'},
    {'code': 'SX', 'name': 'Saint Martin (Netherlands)', 'demonym': ''},
    {'code': 'SY', 'name': 'Syria', 'demonym': 'Syrian'},
    {'code': 'SZ', 'name': 'Swaziland', 'demonym': 'Swazi'},
    {'code': 'TC', 'name': 'Turks and Caicos Islands', 'demonym': 'Turks and Caicos Islander'},
    {'code': 'TD', 'name': 'Chad', 'demonym': 'Chadian'},
    {'code': 'TF', 'name': 'French Southern Territories', 'demonym': ''},
    {'code': 'TG', 'name': 'Togo', 'demonym': 'Togolese'},
    {'code': 'TH', 'name': 'Thailand', 'demonym': 'Thai'},
    {'code': 'TJ', 'name': 'Tajikistan', 'demonym': 'Tajikistani'},
    {'code': 'TK', 'name': 'Tokelau', 'demonym': 'Tokelauan'},
    {'code': 'TL', 'name': 'Timor-Leste', 'demonym': 'Timorese'},
    {'code': 'TM', 'name': 'Turkmenistan', 'demonym': 'Turkmen'},
    {'code': 'TN', 'name': 'Tunisia', 'demonym': 'Tunisian'},
    {'code': 'TO', 'name': 'Tonga', 'demonym': 'Tongan'},
    {'code': 'TR', 'name': 'Turkey', 'demonym': 'Turkish'},
    {'code': 'TT', 'name': 'Trinidad and Tobago', 'demonym': 'Trinidadian'},
    {'code': 'TV', 'name': 'Tuvalu', 'demonym': 'Tuvaluan'},
    {'code': 'TW', 'name': 'Taiwan', 'demonym': 'Taiwanese'},
    {'code': 'TZ', 'name': 'Tanzania', 'demonym': 'Tanzanian'},
    {'code': 'UA', 'name': 'Ukraine', 'demonym': 'Ukrainian'},
    {'code': 'UG', 'name': 'Uganda', 'demonym': 'Ugandan'},
    {'code': 'UM', 'name': 'United States Minor Outlying Islands', 'demonym': ''},
    {'code': 'US', 'name': 'United States of America', 'demonym': 'American'},
    {'code': 'UY', 'name': 'Uruguay', 'demonym': 'Uruguayan'},
    {'code': 'UZ', 'name': 'Uzbekistan', 'demonym': 'Uzbekistani'},
    {'code': 'VA', 'name': 'Vatican', 'demonym': ''},
    {'code': 'VC', 'name': 'Saint Vincent and Grenadines', 'demonym': 'Saint Vincentian'},
    {'code': 'VE', 'name': 'Venezuela', 'demonym': 'Venezuelan'},
    {'code': 'VG', 'name': 'British Virgin Islands', 'demonym': 'Virgin Islander'},
    {'code': 'VI', 'name': 'United States Virgin Islands', 'demonym': 'Virgin Islander'},
    {'code': 'VN', 'name': 'Vietnam', 'demonym': 'Vietnamese'},
    {'code': 'VU', 'name': 'Vanuatu', 'demonym': 'Ni-Vanuatu'},
    {'code': 'WF', 'name': 'Wallis and Futuna Islands', 'demonym': 'Wallisian'},
    {'code': 'WS', 'name': 'Samoa', 'demonym': 'Samoan'},
    {'code': 'YE', 'name': 'Yemen', 'demonym': 'Yemeni'},
    {'code': 'YT', 'name': 'Mayotte', 'demonym': 'Mahoran'},
    {'code': 'ZA', 'name': 'South Africa', 'demonym': 'South African'},
    {'code': 'ZM', 'name': 'Zambia', 'demonym': 'Zambian'},
    {'code': 'ZW', 'name': 'Zimbabwe', 'demonym': 'Zimbabwean'}]
