# Generated by Django 2.2.7 on 2019-11-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_auto_20191126_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'permissions': (('can_create_assignment', 'Create assignment'), ('can_view_assignment', 'View assignment'), ('can_update_assignment', 'Update assignment'), ('can_delete_assignment', 'Delete assignment'))},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'permissions': (('can_create_missions', 'Create missions'), ('can_view_missions', 'View missions'), ('can_update_missions', 'Update missions'), ('can_delete_missions', 'Delete missions'))},
        ),
    ]
